openapi: 3.0.0
info:
  title: yoksis
  version: '1.0'
  description: Mock API service for YOKSIS
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
servers:
  - url: 'http://localhost:3000/yoksis'
    description: YOKSIS
paths:
  /references/administrative_functions:
    get:
      summary: Get the Reference of Administrative Functions
      tags: []
      operationId: get-references-administrative_functions
      description: Returns the reference of administrative functions provided by YOKSIS.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Rector
                    - code: 2
                      name: Dean
                    - code: 3
                      name: Head of the Department
  /references/administrative_units:
    get:
      summary: Get the Reference of Administrative Units
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Council of Higher Education
                    - code: 2
                      name: University of ACME
                    - code: 3
                      name: Rectorship
      operationId: get-references-administrative_units
      description: Returns the reference of administrative units provided by YOKSIS.
  /references/cities:
    get:
      summary: Get the Reference of Cities
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Gotham City
                    - code: 2
                      name: Metropolis
                    - code: 3
                      name: Riverdale
                example-2:
                  value:
                    - code: 101
                      name: Basin City
                    - code: 102
                      name: Star City
                    - code: 103
                      name: Central City
      operationId: get-references-cities
      description: Returns the reference of cities provided by YOKSIS.
  /references/countries:
    get:
      summary: Get the Reference of Countries
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Atlantis
                    - code: 2
                      name: Bacteria
                    - code: 3
                      name: Marley
                example-2:
                  value:
                    - code: 101
                      name: Dinotopia
                    - code: 102
                      name: Eurasia
                    - code: 103
                      name: Oceania
      operationId: get-references-countries
      description: Returns the reference of countries provided by YOKSIS.
  /references/entrance_types:
    get:
      summary: Get the Reference of Entrance Types
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Erasmus
                    - code: 2
                      name: Farabi
                    - code: 3
                      name: Mevlana
      operationId: get-references-entrance_types
      description: Returns the reference of entrance types provided by YOKSIS.
  /references/formations:
    get:
      summary: Get the Reference of Formations
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Biology
                    - code: 2
                      name: Geography
                    - code: 3
                      name: Philosophy
      operationId: get-references-formations
      description: Returns the reference of formations provided by YOKSIS.
  /references/gender:
    get:
      summary: Get the Reference of Gender
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Female
                    - code: 2
                      name: Male
      operationId: get-references-gender
      description: Returns the reference of gender provided by YOKSIS.
  /references/index_types:
    get:
      summary: Get the Reference of Index Types
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: AHCI
                    - code: 2
                      name: SCI
                    - code: 3
                      name: SSCI
      operationId: get-references-indexes
      description: Returns the reference of index types provided by YOKSIS.
    parameters: []
  /references/martyrs_relatives:
    get:
      summary: "Get the Reference of Martyr's Relatives"
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: 'Yes'
                    - code: 2
                      name: 'No'
      operationId: get-references-martyrs_relatives
      description: "Returns the reference of martyr's relatives provided by YOKSIS."
  /references/nationalities:
    get:
      summary: Get the Reference of Nationalities
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Atlantis
                    - code: 2
                      name: Bacteria
                    - code: 3
                      name: Marley
                example-2:
                  value:
                    - code: 101
                      name: Dinotopia
                    - code: 102
                      name: Eurasia
                    - code: 103
                      name: Oceania
      operationId: get-references-nationalities
      description: Returns the reference of nationalities provided by YOKSIS.
  /references/staff_appointment_types:
    get:
      summary: Get the Reference of Staff Appointment Types
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: DUS
                    - code: 2
                      name: EUS
                    - code: 3
                      name: TUS
      operationId: get-references-staff_appointment_types
      description: Returns the reference of staff appointment types provided by YOKSIS.
  /references/staff_duty_types:
    get:
      summary: Get the Reference of Staff Duty Types
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: DUS
                    - code: 2
                      name: EUS
                    - code: 3
                      name: TUS
        '':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Dean
                    - code: 2
                      name: Faculty Secretary
                    - code: 3
                      name: Head of Department
      operationId: get-references-staff_dropout_types
      description: Returns the reference of staff duty types provided by YOKSIS.
    parameters: []
  /references/staff_titles:
    get:
      summary: Get the Reference of Staff Titles
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Associate Professor
                    - code: 2
                      name: Professor
                    - code: 3
                      name: Researcher
      operationId: get-references-staff_titles
      description: Returns the reference of staff titles provided by YOKSIS.
  /references/student_disability_types:
    get:
      summary: Get the Reference of Student Disability Types
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Hearing impaired
                    - code: 2
                      name: Mentally disabled
                    - code: 3
                      name: Partially-sighted
      operationId: get-references-student_disability_types
      description: Returns the reference of student disability types provided by YOKSIS.
  /references/student_dropout_types:
    get:
      summary: Get the Reference of Student Dropout Types
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Farabi
                    - code: 2
                      name: Mevlana
                    - code: 3
                      name: Internal Transfer
      operationId: get-references-student_dropout_types
      description: Returns the reference of student dropout types provided by YOKSIS.
  /references/student_education_levels:
    get:
      summary: Get the Reference of Student Education Levels
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Associate Degree
                    - code: 2
                      name: Undergraduate
                    - code: 3
                      name: Postgraduate
      operationId: get-references-student_education_levels
      description: Returns the reference of student education levels provided by YOKSIS.
  /references/student_entrance_point_types:
    get:
      summary: Get the Reference of Student Entrance Point Types
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: MF
                    - code: 2
                      name: SAY
                    - code: 3
                      name: SOZ
      operationId: get-references-student_entrance_point_types
      description: Returns the reference of student entrance point types provided by YOKSIS.
  /references/student_entrance_types:
    get:
      summary: Get the Reference of Student Entrance Types
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: DGS
                    - code: 2
                      name: Farabi
                    - code: 3
                      name: Internal Transfer
      operationId: get-references-student_entrance_types
      description: Returns the reference of student entrance types provided by YOKSIS.
  /references/student_grades:
    get:
      summary: Get the Reference of Student Grades
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Freshman
                    - code: 2
                      name: Sophomore
                    - code: 3
                      name: Junior
                    - code: 4
                      name: Senior
      operationId: get-references-student_grades
      description: Returns the reference of student grades provided by YOKSIS.
  /references/student_grading_systems:
    get:
      summary: Get the Reference of Student Grading Systems
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Average
                    - code: 2
                      name: Excellent
                    - code: 3
                      name: Good
      operationId: get-references-student_grading_systems
      description: Returns the reference of student grading systems provided by YOKSIS.
  /references/student_punishment_types:
    get:
      summary: Get the Reference of Student Punishment Types
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Prisoner
                    - code: 2
                      name: Reprimand
                    - code: 3
                      name: Rusticated
      operationId: get-references-student_punishment_types
      description: Returns the reference of student punishment types provided by YOKSIS.
  /references/studentship_rights:
    get:
      summary: Get the Reference of Studentship Rights
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: 'Yes'
                    - code: 2
                      name: 'No'
      operationId: get-references-studentship_rights
      description: Returns the reference of studentship rights provided by YOKSIS.
  /references/studentship_statuses:
    get:
      summary: Get the Reference of Studentship Statuses
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Active
                    - code: 2
                      name: Passive
                    - code: 3
                      name: Punished
      operationId: get-references-studentship_statuses
      description: Returns the reference of studentship statuses provided by YOKSIS.
  /references/unit_instruction_languages:
    get:
      summary: Get the Reference of Unit Instruction Languages
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Turkish
                    - code: 2
                      name: English
                    - code: 3
                      name: French
      operationId: get-references-unit_instruction_languages
      description: Returns the reference of unit instruction languages provided by YOKSIS.
  /references/unit_statuses:
    get:
      summary: Get the Reference of Unit Statuses
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Active
                    - code: 2
                      name: Passive
                    - code: 3
                      name: Archived
      operationId: get-references-unit_statuses
      description: Returns the reference of unit statuses provided by YOKSIS.
  /references/unit_types:
    get:
      summary: Get the Reference of Unit Types
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Faculty
                    - code: 2
                      name: Institution
                    - code: 3
                      name: University
      operationId: get-references-unit_types
      description: Returns the reference of unit types provided by YOKSIS.
  /references/university_types:
    get:
      summary: Get the Reference of University Types
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CodeName'
              examples:
                example-1:
                  value:
                    - code: 1
                      name: Foundation Universities
                    - code: 2
                      name: State Universities
                    - code: 3
                      name: Others
      operationId: get-references-university_types
      description: Returns the reference of university types provided by YOKSIS.
components:
  schemas:
    CodeName:
      title: ''
      type: object
      description: "Base Model of References' Response"
      x-examples: {}
      properties:
        code:
          type: number
        name:
          type: string
      required:
        - code
        - name
  securitySchemes: {}